server:
  port: 9000

spring:
  banner:
    location: banner-prod.txt
  application:
    name: bucketPlace
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 30MB

  datasource:
    url: jdbc:mysql://database-1.cq0eqrcd38cr.ap-northeast-2.rds.amazonaws.com/bucket_place?autoReconnect=true
    username: admin
    password: Ovsj0Odmkg
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
  sql:
    init:
      platform: mysql

  mail:
    host: smtp.gmail.com
    port: 587
    username: koc2827@gmail.com
    password: pbvmfwpmnntkjjyv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

cloud:
  aws:
    s3:
      bucket: bucketplace

    # 비밀키 안보이게 처리하기
    credentials:
      access-key: AKIAV54WGIQ3SFO57CEA
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

